### ISSUE TITLE
Use events for reindexing

### ISSUE THREAD

**Issue by michwill** [zero-db/zerodb#21]
Right now, when changes are made to a document or object, one should run re-index manually (and commit).

That's not very convenient. It's much better to fire a zope event on change and put changes in a queue. At the commit event, the objects (or rather just changed fields) should be re-indexed automatically. Perhaps, good library to look at is [collective.indexing](https://github.com/plone/collective.indexing)

**Comment by xueyumusic** [comment]
Currently reindex seems to be called through dbmodel's _catalog attribute. Is there another way to call reindex or maybe could add reindex api in db.py

**Comment by michwill** [comment]
Yes, very good point!

**Comment by xueyumusic** [comment]
I implement this auto-reindex in this [pr](https://github.com/zero-db/zerodb/pull/28) based on collective.indexing

**Comment by michwill** [comment]
Awesome, thanks @xueyumusic ! Cleaned it up removing unnecessary Plone-specific things even further
