### ISSUE TITLE
Make a pip package

### ISSUE THREAD

**Issue by michwill** [zero-db/zerodb#4]
Can put it out here https://pypi.python.org/pypi/zerodb/

**Comment by pemmasanikrishna** [comment]
Hi michwill, I would like to create pip. can you give me the credentials so that I can host it at https://pypi.python.org/pypi/zerodb/

**Comment by michwill** [comment]
Eh, I think this one I'd prefer to do myself.

Though which OS do you have? Maybe you can test afterwards, since I have only Linux :-) Or even now, with clean install and setup.py (to make sure nothing is forgotten in the dependencies etc).

**Comment by michwill** [comment]
[Here we go](https://pypi.python.org/pypi/zerodb/)
